### ISSUE TITLE
Press Ctrl-c  to undefined

### ISSUE THREAD

**Issue by HankLiang** [xiaokaike/vue-clipboard#1]
I have visited [Demo](http://xiaokaike.github.io/vue-clipboard/) on Chrome and Firefox  browser， after I click the copy button, tooltip mssage will show 'Press Ctrl-c  to undefined'. Why?

**Comment by xiaokaike** [comment]
What system

**Comment by HankLiang** [comment]
@xiaokaike ubuntu
