### ISSUE TITLE
Vue 2.0 support

### ISSUE THREAD

**Issue by pbelyaev** [xiaokaike/vue-clipboard#4]
Now it has this error:
```console
Uncaught TypeError: Cannot read property 'bind' of undefined
```

**Comment by xiaokaike** [comment]
unsupport

**Comment by MHLut** [comment]
@pbelyaev I ran into this as well. Looked through the code of this module and noticed it's based on [Clipboard.js](https://clipboardjs.com/). My quick-fix was to wrap Clipboard.js functionality in a Vue.js 2 directive. Like so:

In app.js:
```
[...]

Vue.directive(
    'clipboard',
    require('./directives/clipboard.js')
);

[...]
```

In directives/clipboard.js:
```
var Clipboard = require('clipboard');

module.exports = {
    bind(el, binding, vnode, oldVnode) {
        new Clipboard(el);
    }
}
```

In Vue component:
```
<button id="foo" :data-clipboard-text="result" v-clipboard>Bar</button>
```

I haven't tested on an input/textarea yet, but I suppose you can use the `data-clipboard-action` attribute to set copy mode to copy or cut. (This was a quick-fix for me and I only need a copy button, nothing else).

**Comment by pbelyaev** [comment]
@MHLut thanks.

**Comment by nicokruger** [comment]
Brilliant @MHLut thanks!

You just saved me going to back to an old textarea-that-updates then select-a-ctrl-c approach :)
