### ISSUE TITLE
Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by mesqueeb** [xiaokaike/vue-clipboard#6]
I got:
> Error in directive clipboard bind hook: "TypeError: Cannot read property 'bind' of undefined"

**Comment by sutra** [comment]
I believe this lib does not support `vue2` but you're using it with `vue2`.

By the way, I am currently using [`vue-clipboards`](https://github.com/zhuowenli/vue-clipboards) lib instead. And for the tooltip `Copied!`, see [`primer-css`](http://primercss.io/tooltips/).

**Comment by mesqueeb** [comment]
It doesn't support Vuejs 2! I see!!
